const test = require('node:test');
const assert = require('node:assert/strict');
test('Selection tracks are exact snapshot data; URL pins and canonical ownership protect hydration', async () => {
  const { fetchSelectionVod } = await import('../supabase/functions/_shared/selection-vod.mjs');
  const { discoverySourceId } = await import('../supabase/functions/_shared/discovery-catalog.mjs');
  const { selectionSnapshotFileTags, selectionSnapshotMovieManifests, hydrateSelectionSnapshotMovieTracks } = await import('../supabase/functions/_shared/selection-snapshot-tracks.mjs');
  const sourceId=await discoverySourceId('owner');
  const rows=(await fetchSelectionVod({fetchPlaylist:async()=>{throw Error('unavailable');}})).items.map(e=>e.fields);
  const row=rows.find(r=>r.title==='White Chicks (2004)');
  const tags=await selectionSnapshotFileTags(row.external_id);
  assert.deepEqual(tags.audioLanguages,['es']);
  assert.equal(tags.audioTracksScope,'file');
  assert.ok(!JSON.stringify(tags).includes('https://'));
  assert.deepEqual(await selectionSnapshotFileTags('unreviewed'),{});
  const calls=[];
  const db={from(){throw Error('No read-then-upsert race is allowed');},async rpc(name,args){calls.push({name,args});return {data:args.p_files.length,error:null};}};
  const generationFence={p_generation_id:'current-generation',p_head_revision:4,p_config_revision:2,p_source_visibility_epoch:1,p_user_visibility_epoch:3};
  const args={db,userId:'owner',sourceId,rows:[row],generationFence};
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks({...args,sourceId:'foreign'}),{seeded:0});
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks({...args,rows:[{...row,playback_hint:{targetUrl:'https://unreviewed.example/file.mp4'}}]}),{seeded:0});
  assert.equal(calls.length,0);
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks(args),{seeded:1});
  assert.deepEqual(calls.map(c=>c.name),['hydrate_selection_snapshot_movie_languages']);
  assert.equal(calls[0].args.p_generation_id,'current-generation');
  assert.equal(calls[0].args.p_source_id,sourceId);
  const manifest=calls[0].args.p_files[0];
  assert.equal(manifest.externalId,row.external_id);
  assert.deepEqual(manifest.audioTracks.map(t=>t.lang),['es']);
  tags.audioTracks[0].lang='fr';
  assert.equal((await selectionSnapshotMovieManifests([row]))[0].audioTracks[0].lang,'es','playback tag callers cannot mutate seed evidence');
  assert.match(manifest.urlSha256,/^[a-f0-9]{64}$/);
  assert.equal(manifest.revision,'selection-vod-20260906-v1');
  assert.ok(manifest.probedAt);
  assert.ok(!JSON.stringify(manifest).includes('https://'));
  assert.deepEqual(await selectionSnapshotMovieManifests([{...row,metadata:{audioLanguages:['fr'],codecProfile:{audioTracks:[{index:44,language:'fr'}]}}}]),[manifest],
    'editable metadata cannot replace the published snapshot');
  assert.equal((await selectionSnapshotMovieManifests([row,row])).length,1,'replayed rows are deduplicated');
  const copies=await selectionSnapshotMovieManifests([row]);copies[0].audioTracks[0].lang='fr';
  assert.equal((await selectionSnapshotMovieManifests([row]))[0].audioTracks[0].lang,'es','callers cannot mutate the immutable snapshot');
  await assert.rejects(hydrateSelectionSnapshotMovieTracks({...args,generationFence:null}),/requires a catalogue generation/);
  const realRpc=db.rpc;db.rpc=async()=>({data:0,error:null});
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks(args),{seeded:0});
  db.rpc=realRpc;calls.length=0;
  const allManifests=await selectionSnapshotMovieManifests(rows);
  const eligible=new Set(allManifests.slice(0,120).map(m=>m.externalId));
  await hydrateSelectionSnapshotMovieTracks({...args,rows:rows.filter(r=>eligible.has(r.external_id))});
  const batches=calls.filter(c=>c.name==='hydrate_selection_snapshot_movie_languages');
  assert.equal(batches.length,3);
  assert.ok(batches.every(c=>c.args.p_files.length<=50));
  assert.equal(batches.reduce((n,c)=>n+c.args.p_files.length,0),120);
  calls.length=0;
  await assert.rejects(hydrateSelectionSnapshotMovieTracks({...args,assertSourceCurrent:async()=>{throw Error('source changed');}}),/source changed/);
  assert.equal(calls.length,0,'a stale source must fail before mutation');
  db.rpc=async()=>({error:new Error('stale generation')});
  await assert.rejects(hydrateSelectionSnapshotMovieTracks(args),/stale generation/);
});

 test('Selection playback tags bind the owned source and physical URL and expose the measured episode duration', async()=>{
  const {fetchSelectionVod}=await import('../supabase/functions/_shared/selection-vod.mjs');
  const {discoverySourceId}=await import('../supabase/functions/_shared/discovery-catalog.mjs');
  const {selectionSnapshotPlaybackTags}=await import('../supabase/functions/_shared/selection-snapshot-tracks.mjs');
  const rows=(await fetchSelectionVod({fetchPlaylist:async()=>{throw Error('unavailable')}})).items.map(r=>r.fields);
  const row=rows.find(r=>r.metadata.selectionVodTitle==='Suits S02E01');assert.ok(row);
  const args={userId:'owner',sourceId:await discoverySourceId('owner'),itemId:row.external_id,targetUrl:row.playback_hint.targetUrl};
  const tags=await selectionSnapshotPlaybackTags(args);assert.deepEqual(tags.audioLanguages,['es']);
  assert.ok(tags.codecProfile.durationSeconds>2500);assert.ok(tags.codecProfile.probedAt);assert.equal(tags.codecProfile.probeSource,'selection-container-audit');
  assert.ok(!JSON.stringify(tags).includes('https://'));
  let cached={audio_tracks:[{index:1,lang:'en'}],audio_probed_at:'2026-09-08',audio_lang_verified_at:'2026-09-08',audio_lang_verification:{status:'verified'}};
  let error=null;
  const db={from(table){assert.equal(table,'catalog_file_tracks');const query={select(){return query},eq(){return query},async maybeSingle(){return {data:cached,error}}};return query;}};
  const newer=await selectionSnapshotPlaybackTags({...args,itemType:'movie',db});
  assert.deepEqual(newer.audioLanguages,['en']);assert.equal(newer.audioLanguageValidationStatus,'verified');
  assert.equal(newer.codecProfile.audioTracks[0].language,'en');
  cached={audio_tracks:[{index:1,lang:null}],audio_probed_at:'2026-09-08'};
  const unknown=await selectionSnapshotPlaybackTags({...args,itemType:'movie',db});
  assert.deepEqual(unknown.audioLanguages,[]);assert.equal(unknown.audioLanguageValidationStatus,'pending');
  error=new Error('unavailable');assert.deepEqual(await selectionSnapshotPlaybackTags({...args,itemType:'movie',db}),{});
  assert.deepEqual(await selectionSnapshotPlaybackTags({...args,userId:'foreign'}),{});
  assert.deepEqual(await selectionSnapshotPlaybackTags({...args,targetUrl:'https://unreviewed.example/other.mp4'}),{});
  assert.deepEqual(await selectionSnapshotPlaybackTags({...args,itemId:'unknown'}),{});
 });
