const test = require('node:test');
const assert = require('node:assert/strict');
test('Selection tracks are exact snapshot data; URL pins and canonical ownership protect hydration', async () => {
  const { fetchSelectionVod } = await import('../supabase/functions/_shared/selection-vod.mjs');
  const { discoverySourceId } = await import('../supabase/functions/_shared/discovery-catalog.mjs');
  const { selectionSnapshotFileTags, hydrateSelectionSnapshotMovieTracks } = await import('../supabase/functions/_shared/selection-snapshot-tracks.mjs');
  const sourceId=await discoverySourceId('owner');
  const rows=(await fetchSelectionVod({fetchPlaylist:async()=>{throw Error('unavailable');}})).items.map(e=>e.fields);
  const row=rows.find(r=>r.title==='White Chicks (2004)');
  const tags=await selectionSnapshotFileTags(row.external_id);
  assert.deepEqual(tags.audioLanguages,['es']);
  assert.equal(tags.audioTracksScope,'file');
  assert.ok(!JSON.stringify(tags).includes('https://'));
  assert.deepEqual(await selectionSnapshotFileTags('unreviewed'),{});
  let cached=false,observed=false;const calls=[];
  const db={from(table){const q={select(){return q;},eq(){return q;},in(_column,values){assert.ok(values.length<=50, "long Selection IDs must stay below the proxy URI limit");return q;},then(resolve,reject){return Promise.resolve({data:table==='catalog_file_tracks'?(cached?[{external_id:row.external_id,audio_probed_at:'2026-09-07'}]:[]):table==='cloud_catalog_visible_title_variants'?[{id:'variant',external_id:row.external_id}]:observed?[{variant_id:'variant',audio_observed:true}]:[],error:null}).then(resolve,reject);}};return q;},async rpc(name,args){calls.push({name,args});return {data:1,error:null};}};
  const generationFence={p_generation_id:'current-generation',p_head_revision:4,p_config_revision:2,p_source_visibility_epoch:1,p_user_visibility_epoch:3};
  const args={db,userId:'owner',sourceId,rows:[row],generationFence};
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks({...args,sourceId:'foreign'}),{seeded:0});
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks({...args,rows:[{...row,playback_hint:{targetUrl:'https://unreviewed.example/file.mp4'}}]}),{seeded:0});
  assert.equal(calls.length,0);
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks(args),{seeded:1});
  assert.deepEqual(calls.map(c=>c.name),['upsert_catalog_file_tracks','hydrate_cloud_title_file_languages']);
  assert.equal(calls[0].args.p_server_host,'source:'+sourceId);
  assert.equal(calls[1].args.p_generation_id,'current-generation');
  assert.equal(calls[1].args.p_source_id,sourceId);
  assert.deepEqual(calls[1].args.p_external_ids,[row.external_id]);
  await assert.rejects(hydrateSelectionSnapshotMovieTracks({...args,generationFence:null}),/requires a catalogue generation/);
  cached=true;calls.length=0;
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks(args),{seeded:1});
  assert.deepEqual(calls.map(c=>c.name),['hydrate_cloud_title_file_languages'],'resume fanout without replacing the cached probe');
  observed=true;calls.length=0;
  assert.deepEqual(await hydrateSelectionSnapshotMovieTracks(args),{seeded:0});
  assert.equal(calls.length,0,'later speech verification and retry state are preserved');
  observed=false;calls.length=0;
  await hydrateSelectionSnapshotMovieTracks({...args,rows:rows.filter(r=>r.item_type==='movie'&&r.metadata.codecProfile?.audioTracks?.length).slice(0,120)});
  const batches=calls.filter(c=>c.name==='hydrate_cloud_title_file_languages');
  assert.equal(batches.length,3);
  assert.ok(batches.every(c=>c.args.p_external_ids.length<=50));
  assert.equal(batches.reduce((n,c)=>n+c.args.p_external_ids.length,0),120);
  db.rpc=async()=>({error:new Error('stale generation')});
  await assert.rejects(hydrateSelectionSnapshotMovieTracks(args),/stale generation/);
});
