'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { buildSync } = require('esbuild');
const root = path.resolve(__dirname, '../..');
const checkOnly = process.argv.includes('--check');
const locales = require('../../i18n/locales.json');
const messages = require('../../i18n/messages.json');
const catalogTools = require('./catalog.cjs');
const catalog = catalogTools.load();
catalogTools.validate(catalog);
require('./build-native.cjs');
const placeholders = value => [...value.matchAll(/\{\{(\w+)\}\}/g)].map(m => m[1]).sort().join(',');
const xml = value => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/'/g, "\\'").replace(/"/g, '\\"');
for (const [key, translations] of Object.entries(messages)) {
    if (!/^ui_[a-z0-9_]+$/.test(key)) throw new Error(`Invalid resource key: ${key}`);
    if (translations.length !== locales.length) throw new Error(`${key}: expected ${locales.length} translations`);
    for (const value of translations) {
        if (typeof value !== 'string' || !value.trim()) throw new Error(`${key}: empty translation`);
        if (placeholders(value) !== placeholders(translations[0])) throw new Error(`${key}: mismatched placeholders`);
    }
}
function write(relative, content) {
    const target = path.join(root, relative);
    if (checkOnly) {
        const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : null;
        if (existing !== content.replace(/\r\n/g, '\n')) throw new Error(`Stale generated file: ${relative}. Run npm run i18n:build.`);
        return;
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) fs.writeFileSync(target, content);
}
for (const [index, locale] of locales.entries()) {
    const strings = Object.entries(messages).map(([key, values]) => `    <string name="${key}" formatted="false">${xml(values[index])}</string>`);
    write(`clients/android-common/src/main/res/${locale.android}/norva_ui.xml`,
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by npm run i18n:build. Edit i18n/messages.json. -->\n<resources>\n' + strings.join('\n') + '\n</resources>\n');
}
write('clients/android-common/src/main/res/xml/norva_locales.xml',
    '<?xml version="1.0" encoding="utf-8"?>\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n'
    + locales.map(l => `    <locale android:name="${l.code}" />`).join('\n') + '\n</locale-config>\n');
const bundle = buildSync({
    write: false,
    stdin: { contents: fs.readFileSync(path.join(root, 'i18n/runtime.js'), 'utf8').replace(/import webBase[\s\S]*?const webMessages = [^;]+;/, () => 'const webMessages = '+JSON.stringify(Object.fromEntries(Object.entries(catalog).map(([k,e])=>[k,Object.fromEntries(locales.map(l=>[l.code,e[l.code]]))])))+';'), resolveDir: path.join(root,'i18n'), sourcefile: 'runtime.js' },
    outfile: path.join(root, 'public/js/i18n.js'), bundle: true, minify: true,
    format: 'iife', target: ['chrome80'], legalComments: 'eof',
    banner: { js: '/* Generated by npm run i18n:build; includes i18next (MIT). */' },
    footer: { js: '/*\n' + fs.readFileSync(path.join(root, 'node_modules/i18next/LICENSE'), 'utf8') + '\n*/' },
});
write('public/js/i18n.js', bundle.outputFiles[0].text);
// Update only this feature's asset references, preserving unrelated dirty pages.
const hashes = Object.fromEntries(['js/i18n.js', 'css/i18n.css'].map(file => [file,
    crypto.createHash('sha256').update(fs.readFileSync(path.join(root, 'public', file), 'utf8').replace(/\r\n/g, '\n')).digest('hex').slice(0, 10)]));
function htmlFiles(dir = '') { return fs.readdirSync(path.join(root,'public',dir), {withFileTypes:true}).flatMap(entry => entry.isDirectory() ? htmlFiles(path.join(dir,entry.name)) : entry.name.endsWith('.html') ? [path.join(dir,entry.name)] : []); }
for (const file of htmlFiles()) {
    const full = path.join(root, 'public', file);
    const source = fs.readFileSync(full, 'utf8');
    const next = source.replace(/\/(js\/i18n\.js|css\/i18n\.css)\?v=[^"']+/g, (_, asset) => `/${asset}?v=${hashes[asset]}`);
    if (next !== source) {
        if (checkOnly) throw new Error(`Stale i18n asset reference: ${file}`);
        fs.writeFileSync(full, next);
    }
}
console.log(`Built ${(Object.keys(messages).length + Object.keys(catalog).length)} messages in ${locales.length} languages for web and Android.`);
