'use strict';
const fs=require('fs'),path=require('path'),acorn=require('acorn');const root=path.resolve(__dirname,'../..');
const catalog={...require('../../i18n/web-tail.json'),...require('../../i18n/web-dynamic.json'),...require('../../i18n/web-extra.json'),...require('../../i18n/web.json')};
function rewrite(source){const tree=acorn.parse(source,{ecmaVersion:'latest',sourceType:'module'}),edits=[];
function visit(n, ancestors=[]){if(!n||typeof n!=='object')return;if(n.type==='Literal'&&typeof n.value==='string'&&/<[a-z][\s\S]*>/i.test(n.value)&&source[n.start]==='"'){edits.push({start:n.start,end:n.end,text:"'"+n.value.replaceAll('\\','\\\\').replaceAll("'","\\'").replaceAll('\r','\\r').replaceAll('\n','\\n')+"'"});return;}
if(n.type==='CallExpression'&&n.callee.property?.name==='t'&&n.callee.object?.property?.name==='NorvaI18n'){const key=n.arguments[0]?.value;const entry=catalog[key];if(entry){const fallback=ancestors.findLast(a=>a.type==='LogicalExpression'&&a.operator==='??'&&a.right?.type==='Literal'&&typeof a.right.value==='string')?.right.value;const defaultCopy=fallback&&fallback.replace(/\s+/g,' ').trim()===entry.source?fallback:entry.source;const options=n.arguments[1];if(!options){edits.push({start:n.end-1,end:n.end-1,text:', { defaultValue: '+JSON.stringify(defaultCopy)+' }'});}else if(options.type==='ObjectExpression'&&options.properties.some(p=>(p.key.name||p.key.value)==='defaultValue'&&p.value.value!==defaultCopy)){const prop=options.properties.find(p=>(p.key.name||p.key.value)==='defaultValue');edits.push({start:prop.value.start,end:prop.value.end,text:JSON.stringify(defaultCopy)});}else if(options.type==='ObjectExpression'&&!options.properties.some(p=>(p.key.name||p.key.value)==='defaultValue')){edits.push({start:options.start+1,end:options.start+1,text:'defaultValue: '+JSON.stringify(defaultCopy)+(options.properties.length?', ':'')});}}}
for(const [k,c]of Object.entries(n)){if(['start','end'].includes(k))continue;if(Array.isArray(c))c.forEach(child=>visit(child,[...ancestors,n]));else if(c&&typeof c==='object')visit(c,[...ancestors,n]);}}
visit(tree);for(const e of edits.sort((a,b)=>b.start-a.start))source=source.slice(0,e.start)+e.text+source.slice(e.end);return source.replaceAll('NorvaI18n?.args({','NorvaI18n?.args?.({');}
function walk(d){return fs.readdirSync(path.join(root,d),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]);}
let count=0;for(const p of walk('public/js').filter(p=>p.endsWith('.js')&&!p.includes('/vendor/')&&!p.endsWith('/i18n.js'))){const s=fs.readFileSync(path.join(root,p),'utf8'),out=rewrite(s);if(out!==s){fs.writeFileSync(path.join(root,p),out);count++;}}
for(const p of fs.readdirSync(path.join(root,'public')).filter(p=>p.endsWith('.html'))){const f=path.join(root,'public',p),s=fs.readFileSync(f,'utf8');const out=s.replace(/(<script\b[^>]*>)([\s\S]*?)(<\/script>)/g,(all,o,s,c)=>!s.trim()||/type=["'](?:application\/|importmap)/.test(o)?all:o+rewrite(s)+c);if(out!==s){fs.writeFileSync(f,out);count++;}}
console.log('Preserved fallback compatibility in',count,'files');
