const statusEl=document.querySelector('#status'),metricsEl=document.querySelector('#metrics');
let player, loader, record, interval, records=[], state='idle', seekAt=null, limit;
const clock=()=>performance.now();const safe=val=>JSON.parse(JSON.stringify(val,(_,v)=>typeof v==='bigint'?Number(v):v));
const originalFetch=window.fetch.bind(window);window.fetch=async(input,options={})=>{const u=new URL(typeof input==='string'?input:input.url,location.href),media=u.origin!==location.origin;const began=clock();try{const r=await originalFetch(input,options);if(record&&media){record.http??=[];record.http.push({method:options.method||'GET',range:new Headers(options.headers).get('range'),status:r.status,contentRange:r.headers.get('content-range'),length:r.headers.get('content-length'),headersMs:Math.round(clock()-began)});}return r;}catch(e){if(record&&media){record.http??=[];record.http.push({method:options.method||'GET',range:new Headers(options.headers).get('range'),error:e.name,ms:Math.round(clock()-began)});}throw e;}};
function show(){const current=record?{...record,samples:record.samples.slice(-4),http:record.http?.slice(-6),events:record.events.slice(-8)}:null;const history=records.map(r=>({copy:r.copy,firstVideoMs:r.firstVideoMs,seekToProgressMs:r.seekToProgressMs,errors:r.errors,expiration:r.expiration}));metricsEl.textContent=JSON.stringify({state,records:history,current},null,2);}
function event(name,extra={}){if(!record)return;record.events.push({name,ms:Math.round(clock()-record.started),...extra});show();}
async function api(path,body){const r=await fetch('/real/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});const j=await r.json();if(!r.ok)throw Error(j.guard||j.code||'Admission refusée');return j;}
async function stop(){if(state==='idle'||state==='closing')return;state='closing';clearInterval(interval);clearTimeout(limit);const closing=record;const closingPlayer=player;player=null;event('operatorStop');show();
 try{await loader?.stop();}catch(e){closing.cleanupError=e.message;}
 const receipt=await api('finish',{metrics:closing});closing.expiration=receipt;closing.finished=true;records.push(closing);await fetch('/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(closing)});record=null;
 try{if(closingPlayer)await Promise.race([closingPlayer.destroy(),new Promise((_,reject)=>setTimeout(()=>reject(Error('destroyTimeout')),15000))]);}catch(e){closing.cleanupError=e.message;}
 state='idle';statusEl.textContent='Lecture arrêtée, accès expiré';show();}
function wasm(type,id){if(type==='resampler')return '/wasm/resample.wasm';if(type==='stretchpitcher')return '/wasm/stretchpitch.wasm';const files={27:'h264',173:'hevc',2:'mpeg2video',12:'mpeg4',86018:'aac',86019:'ac3',86056:'eac3',86017:'mp3'};if(!files[id])return undefined;event('wasmResource',{type,codec:id});return '/wasm/'+files[id]+'.wasm';}
async function start(){if(state!=='idle')return;state='admitting';statusEl.textContent='Préparation de la session…';const option=document.querySelector('#copy').selectedOptions[0],software=document.querySelector('#software').checked;record={copy:option.textContent,index:Number(option.value),software,started:clock(),firstVideoMs:null,firstAudioMs:null,events:[],samples:[],errors:[],crossOriginIsolated:window.crossOriginIsolated};show();
 try{const session=await api('start',{index:record.index,route:'engine',position:0,variant:'avplayer-coalesced'});record.sessionReadyMs=Math.round(clock()-record.started);record.mode=session.mode;record.profile={container:session.codecProfile?.container,video:session.codecProfile?.videoCodec,audio:session.codecProfile?.audioCodec};if(session.mode!=='engine')throw Error('Parcours moteur non admis');
 if(!AVPlayer.audioContext)AVPlayer.audioContext=new AudioContext();await AVPlayer.audioContext.resume();
 record.workerEnabled=true;record.delivery='progressive-2MiB-coalesced64KiB';record.renderSelection='MSE-when-supported';player=new AVPlayer({container:document.querySelector('#screen'),getWasm:wasm,enableWorker:true,enableWebCodecs:!software,enableHardware:!software,enableWebGPU:false,checkUseMSE:()=>!software,preLoadTime:4});player.setVolume(0);state='loading';statusEl.textContent='Préparation de la vidéo…';
 ['loading','loaded','playing','played','paused','seeking','seeked','ended','timeout','error','changed','firstVideoRendered','firstAudioRendered'].forEach(name=>player.on(name,e=>{if(!record||state==='closing'||state==='failed')return;event(name);if(name==='firstVideoRendered'){record.firstVideoMs=Math.round(clock()-record.started);clearTimeout(limit);limit=setTimeout(()=>stop(),180000);}if(name==='firstAudioRendered')record.firstAudioMs=Math.round(clock()-record.started);if(name==='error'){record.errors.push({code:e?.code||e?.error||'decoder-error'});state='failed';statusEl.textContent='Lecture interrompue';clearTimeout(limit);limit=setTimeout(()=>stop(),5000);}if(name==='ended'){state='ended';clearTimeout(limit);limit=setTimeout(()=>stop(),1000);}if(name==='played'){state='playing';statusEl.textContent='Lecture en cours';}}));
 interval=setInterval(()=>{if(!record||!player)return;let stats=safe(player.getStats());const fields=['audioDecodeErrorPacketCount','audioFrameDecodeCount','audioFrameRenderCount','audioFrameRenderIntervalMax','videoDecodeErrorPacketCount','videoFrameDecodeCount','videoFrameRenderCount','videoFrameDropCount','videoFrameRenderIntervalMax','videoStutter','audioStutter','bufferReceiveBytes','bufferOutputBytes','bandwidth','audioCurrentTime','videoCurrentTime','videoRenderFramerate','width','height','sampleRate','channels'];stats=Object.fromEntries(fields.map(k=>[k,stats[k]]));const v=document.querySelector('#screen video');const quality=v?.getVideoPlaybackQuality?.();const nativeVideo=v?{time:v.currentTime,readyState:v.readyState,paused:v.paused,width:v.videoWidth,height:v.videoHeight,frames:quality?.totalVideoFrames,dropped:quality?.droppedVideoFrames,buffered:Array.from({length:v.buffered.length},(_,i)=>[v.buffered.start(i),v.buffered.end(i)])}:null;record.samples.push({ms:Math.round(clock()-record.started),time:Number(player.currentTime),stats,nativeVideo,subtitle:document.querySelector('#screen').innerText.slice(0,300)});const videoTime=nativeVideo?nativeVideo.time*1000:stats.videoCurrentTime;if(nativeVideo?.readyState>=2&&nativeVideo.width>0&&nativeVideo.time>0&&!record.firstVideoMs){record.firstVideoMs=Math.round(clock()-record.started);event('firstNativeVideoObserved');clearTimeout(limit);limit=setTimeout(()=>stop(),180000);}if(seekAt&&videoTime>=120500){record.seekToProgressMs=Math.round(clock()-seekAt);seekAt=null;}show();},500);
 limit=setTimeout(()=>stop(),record.firstVideoMs===null?150000:240000);
 loader=new NorvaAVPlayerRangeLoader(session.url,session.ext||(session.codecProfile?.container?.includes('matroska')?'mkv':'mp4'));await loader.open();record.probeDuration=0.5;await player.load(loader,{maxProbeDuration:record.probeDuration});record.loadMs=Math.round(clock()-record.started);record.tracks=safe(player.getStreams().map(s=>({id:s.id,mediaType:s.mediaType,codec:s.codec,metadata:s.metadata})));await player.play({audio:true,video:true,subtitle:true});show();
 }catch(e){if(record){record.errors.push({stage:state,message: String(e?.name||'Error')});event('preparationRejected');statusEl.textContent='La préparation a échoué';show();}}
}
document.querySelector('#start').onclick=start;
document.querySelector('#seek').onclick=async()=>{if(!player||state!=='playing')return;seekAt=clock();event('seekRequested',{target:120000});await player.seek(120000n);event('seekResolved');};
document.querySelector('#audio').onclick=async()=>{if(!player)return;const streams=player.getStreams().filter(s=>s.mediaType==='Audio');if(streams.length>1){await player.selectAudio(streams[1].id);event('audioSelected',{id:streams[1].id});}};
document.querySelector('#stop').onclick=stop;
