const http=require('node:http'),fs=require('node:fs'),path=require('node:path');const dir=__dirname,root=path.resolve(dir,'../../..'),results=fs.existsSync(path.join(dir,'browser.safe.json'))?JSON.parse(fs.readFileSync(path.join(dir,'browser.safe.json'),'utf8')):[];
const server=http.createServer(async(q,r)=>{let p=new URL(q.url,'http://127.0.0.1').pathname;
if(p.startsWith('/real/')&&q.method==='POST'){if(q.headers.origin!=='http://127.0.0.1:19610'){r.writeHead(403).end();return;}const x=http.request({hostname:'127.0.0.1',port:19611,path:p.slice(5),method:'POST',headers:{'Content-Type':'application/json','Content-Length':q.headers['content-length']},timeout:110000},s=>{r.writeHead(s.statusCode,{'Content-Type':'application/json'});s.pipe(r)});x.on('error',()=>{if(!r.headersSent)r.writeHead(502);r.end('{"error":"Contrôleur indisponible"}')});x.on('timeout',()=>x.destroy());q.pipe(x);return;}
if(p==='/result'&&q.method==='POST'){if(q.headers.origin!=='http://127.0.0.1:19610'){r.writeHead(403).end();return;}let b='';for await(const c of q){b+=c;if(b.length>4e6){r.writeHead(413).end();return;}}results.push(JSON.parse(b));fs.writeFileSync(path.join(dir,'browser.safe.json'),JSON.stringify(results,null,2));r.end('saved');return;}
const aliases={'/':path.join(dir,'index.html'),'/vendor/cheap-polyfill.js':path.join(dir,'dist/cheap-polyfill.js')};let f=aliases[p];if(!f&&p.startsWith('/vendor/'))f=path.join(dir,'npm/package/dist/umd',path.basename(p));if(!f&&p.startsWith('/wasm/')){let name=path.basename(p);f=path.join(dir,'dist',name.startsWith('resample')?'resample':name.startsWith('stretchpitch')?'stretchpitch':'decode',name);}if(!f&&p.startsWith('/norva/'))f=path.join(root,'public',p.slice(7));if(!f)f=path.join(dir,p.slice(1));
f=path.resolve(f);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){r.writeHead(404).end();return;}
const size=fs.statSync(f).size,m=/^bytes=(\d+)-(\d*)$/.exec(q.headers.range||''),start=m?+m[1]:0,end=m?Math.min(+(m[2]||size-1),size-1):size-1;if(start>end){r.writeHead(416,{'Content-Range':`bytes */${size}`}).end();return;}
const type={'.js':'text/javascript','.mjs':'text/javascript','.html':'text/html; charset=utf-8','.css':'text/css','.wasm':'application/wasm','.mkv':'video/x-matroska','.mp4':'video/mp4','.mov':'video/quicktime','.ts':'video/mp2t','.avi':'video/x-msvideo'}[path.extname(f)]||'application/octet-stream';r.writeHead(m?206:200,{'Content-Type':type,'Cache-Control':'no-store','Content-Length':end-start+1,'Accept-Ranges':'bytes',...(m?{'Content-Range':`bytes ${start}-${end}/${size}`}:{})});const s=fs.createReadStream(f,{start,end});r.on('close',()=>s.destroy());s.pipe(r);
});server.listen(19610,'127.0.0.1',()=>console.log('http://127.0.0.1:19610/'));setTimeout(()=>{server.closeAllConnections();server.close()},60*60e3).unref();
