begin;
set local request.jwt.claim.role='service_role';
create temp table qa_results(label text);
create function pg_temp.assert(ok boolean,label text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'Assertion failed: %',label; end if;
 insert into qa_results values(label); end $$;
create function pg_temp.id(n integer) returns uuid language sql immutable as $$select ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.source(n integer,owner integer,account integer,identity integer) returns void language plpgsql as $$
begin
 insert into public.cloud_sources(id,user_id) values(pg_temp.id(n),pg_temp.id(owner));
 insert into public.cloud_catalog_visible_sources values(pg_temp.id(n),pg_temp.id(owner));
 insert into public.cloud_source_catalog_heads values(pg_temp.id(n),pg_temp.id(owner),pg_temp.id(900));
 insert into public.cloud_source_provider_account_affinities values(pg_temp.id(n),pg_temp.id(owner),lpad(account::text,64,'0'),now()-interval '3 hours');
 insert into public.catalog_source_provider_identities values(pg_temp.id(n),pg_temp.id(owner),pg_temp.id(identity),'provider-'||identity,now()-interval '3 hours');
end $$;
create function pg_temp.job(owner integer,identity integer,stage text default 'transcribing') returns void language sql as $$
insert into public.catalog_generated_subtitles(claimed_by,provider_key,status,stage,updated_at,requested_at,resolved_at,enqueued_at)
values(pg_temp.id(owner),pg_temp.id(identity)::text,'processing',stage,now(),now()-interval '1 hour',now()-interval '59 minutes',now()-interval '58 minutes')$$;
create function pg_temp.blocked(owner integer default 1,source integer default 10) returns boolean language sql stable as $$
 select public.catalog_source_account_pregen_active(pg_temp.id(owner),pg_temp.id(source))$$;

select pg_temp.source(10,1,100,1000);
select pg_temp.source(11,1,101,1001);
select pg_temp.source(12,2,100,1002);
select pg_temp.source(13,3,102,1003);
select pg_temp.assert(not pg_temp.blocked(),'idle current source allowed');
select pg_temp.assert(pg_typeof(pg_temp.blocked())='boolean'::regtype,'only boolean returned');
select pg_temp.assert(pg_temp.blocked(2,10),'foreign target blocked');
select pg_temp.assert(pg_temp.blocked(1,99),'missing target blocked');
select pg_temp.assert(public.catalog_source_account_pregen_active(null,pg_temp.id(10)),'missing owner blocked');
select pg_temp.assert(public.catalog_source_account_pregen_active(pg_temp.id(1),null),'missing source blocked');
select pg_temp.job(1,1001);
select pg_temp.assert(not pg_temp.blocked(),'same owner other provider account transcribing does not block');
update public.catalog_generated_subtitles set stage='queued';
select pg_temp.assert(not pg_temp.blocked(),'same owner other provider account queued does not block');
update public.catalog_generated_subtitles set provider_key='provider-1001';
select pg_temp.assert(not pg_temp.blocked(),'verified provider fingerprint resolves distinct account');
update public.catalog_generated_subtitles set provider_key='source:'||pg_temp.id(11);
select pg_temp.assert(not pg_temp.blocked(),'legacy source key resolves distinct account');
update public.catalog_source_provider_identities set verified_at=null where source_id=pg_temp.id(11);
select pg_temp.assert(not pg_temp.blocked(),'legacy source key does not require provider identity');
update public.catalog_generated_subtitles set provider_key=pg_temp.id(1001)::text;
select pg_temp.assert(pg_temp.blocked(),'unverified candidate mapping blocks');
update public.catalog_source_provider_identities set verified_at=now()-interval '3 hours';
update public.cloud_source_provider_account_affinities set updated_at=now() where source_id=pg_temp.id(11);
select pg_temp.assert(pg_temp.blocked(),'credentials changed after admission block');
update public.cloud_source_provider_account_affinities set updated_at=now()-interval '3 hours';
update public.catalog_generated_subtitles set requested_at=null,resolved_at=null,enqueued_at=null;
select pg_temp.assert(pg_temp.blocked(),'unknown admission time blocks');
truncate public.catalog_generated_subtitles;
select pg_temp.job(2,1002);
select pg_temp.assert(pg_temp.blocked(),'same proven account across owners blocks');
update public.catalog_generated_subtitles set stage='queued';
select pg_temp.assert(pg_temp.blocked(),'queued same-account reservation remains blocking');
truncate public.catalog_generated_subtitles;
select pg_temp.job(1,1000);
select pg_temp.assert(pg_temp.blocked(),'same source processing blocks');
update public.catalog_generated_subtitles set status='ready';
select pg_temp.assert(not pg_temp.blocked(),'ready job does not block');
update public.catalog_generated_subtitles set status='failed';
select pg_temp.assert(not pg_temp.blocked(),'failed job does not block');
update public.catalog_generated_subtitles set status='processing',updated_at=now()-interval '2 hours 1 second';
select pg_temp.assert(not pg_temp.blocked(),'existing two hour TTL preserved');
update public.catalog_generated_subtitles set updated_at=now(),provider_key='unknown-relevant';
select pg_temp.assert(pg_temp.blocked(),'unknown job of target owner fails closed');
update public.catalog_generated_subtitles set claimed_by=pg_temp.id(2);
select pg_temp.assert(pg_temp.blocked(),'unknown job of proven same-account owner fails closed');
update public.catalog_generated_subtitles set claimed_by=pg_temp.id(3);
select pg_temp.assert(not pg_temp.blocked(),'unrelated foreign unknown job is not a global veto');
update public.catalog_generated_subtitles set claimed_by=null,provider_key=pg_temp.id(1000)::text;
select pg_temp.assert(pg_temp.blocked(),'known target provider key with unknown owner fails closed');
truncate public.catalog_generated_subtitles;
select pg_temp.job(3,1003);
select pg_temp.assert(not pg_temp.blocked(),'known unrelated foreign job does not block');
update public.catalog_generated_subtitles set provider_key=pg_temp.id(1000)::text;
select pg_temp.assert(pg_temp.blocked(),'potential target key with unresolved foreign mapping fails closed');
update public.catalog_source_provider_identities set identity_id=pg_temp.id(1000) where source_id=pg_temp.id(13);
select pg_temp.assert(not pg_temp.blocked(),'provider-wide identity alone does not imply same account');
truncate public.catalog_generated_subtitles;
select pg_temp.job(1,1001);
select pg_temp.source(14,1,100,1001);
select pg_temp.assert(pg_temp.blocked(),'ambiguous key containing target account blocks');
delete from public.cloud_sources where id=pg_temp.id(14);
delete from public.cloud_source_provider_account_affinities where source_id=pg_temp.id(14);
delete from public.catalog_source_provider_identities where source_id=pg_temp.id(14);
delete from public.cloud_catalog_visible_sources where id=pg_temp.id(11);
select pg_temp.assert(pg_temp.blocked(),'hidden candidate cannot be proved unrelated');
insert into public.cloud_catalog_visible_sources values(pg_temp.id(11),pg_temp.id(1));
update public.cloud_source_catalog_heads set active_generation_id=null where source_id=pg_temp.id(11);
select pg_temp.assert(pg_temp.blocked(),'candidate without current generation blocks');
update public.cloud_source_catalog_heads set active_generation_id=pg_temp.id(900);
delete from public.cloud_source_provider_account_affinities where source_id=pg_temp.id(11);
select pg_temp.assert(pg_temp.blocked(),'candidate affinity missing blocks');
truncate public.catalog_generated_subtitles;
delete from public.cloud_catalog_visible_sources where id=pg_temp.id(10);
select pg_temp.assert(pg_temp.blocked(),'hidden target blocks even idle');
insert into public.cloud_catalog_visible_sources values(pg_temp.id(10),pg_temp.id(1));
update public.cloud_source_catalog_heads set active_generation_id=null where source_id=pg_temp.id(10);
select pg_temp.assert(pg_temp.blocked(),'target without current generation blocks');
update public.cloud_source_catalog_heads set active_generation_id=pg_temp.id(900);
delete from public.cloud_source_provider_account_affinities where source_id=pg_temp.id(10);
select pg_temp.assert(pg_temp.blocked(),'target without affinity blocks');
insert into public.cloud_source_provider_account_affinities values(pg_temp.id(10),pg_temp.id(1),lpad('100',64,'0'),now()-interval '3 hours');
insert into public.cloud_source_provider_account_affinities values(pg_temp.id(11),pg_temp.id(1),lpad('101',64,'0'),now()-interval '3 hours');
update public.catalog_source_provider_identities set verified_at=null where source_id=pg_temp.id(10);
select pg_temp.job(1,1001);
select pg_temp.assert(not pg_temp.blocked(),'target exact affinity does not require unrelated provider identity');
update public.catalog_source_provider_identities set verified_at=now()-interval '3 hours';
truncate public.catalog_generated_subtitles;
select pg_temp.job(1,1001) from generate_series(1,128);
select pg_temp.assert(not pg_temp.blocked(),'128 relevant provably unrelated jobs allowed');
select pg_temp.job(1,1000);
select pg_temp.assert(pg_temp.blocked(),'129th relevant job cannot be truncated away');
truncate public.catalog_generated_subtitles;
select pg_temp.job(3,9999) from generate_series(1,200);
select pg_temp.job(1,1000);
select pg_temp.assert(pg_temp.blocked(),'unrelated jobs cannot consume relevant job limit');
truncate public.catalog_generated_subtitles;
select pg_temp.source(10000+n,4,103,2000) from generate_series(1,129) n;
select pg_temp.source(20000,4,100,2001);
select pg_temp.job(4,2000);
select pg_temp.assert(pg_temp.blocked(),'129 candidate sources fail closed');
truncate public.catalog_generated_subtitles;
select pg_temp.source(30000+n,5,100,3000+n) from generate_series(1,129) n;
select pg_temp.assert(pg_temp.blocked(),'129 related account aliases fail closed');
truncate public.catalog_generated_subtitles;
select pg_temp.source(20,6,106,1006);
update public.cloud_sources set source_type='m3u' where id=pg_temp.id(20);
delete from public.cloud_source_provider_account_affinities where source_id=pg_temp.id(20);
select pg_temp.assert(not pg_temp.blocked(6,20),'M3U idle without affinity retains legacy allow');
select pg_temp.job(3,1003);
select pg_temp.assert(not pg_temp.blocked(6,20),'M3U unrelated owner processing retains legacy allow');
update public.catalog_generated_subtitles set provider_key=pg_temp.id(1006)::text;
select pg_temp.assert(not pg_temp.blocked(6,20),'M3U does not invent cross-owner alias equivalence');
select pg_temp.job(6,9999);
select pg_temp.assert(pg_temp.blocked(6,20),'M3U same-owner unknown processing retains legacy block');
update public.catalog_generated_subtitles set stage='queued';
select pg_temp.assert(pg_temp.blocked(6,20),'M3U same-owner queued retains legacy block');
update public.catalog_generated_subtitles set updated_at=now()-interval '2 hours 1 second';
select pg_temp.assert(not pg_temp.blocked(6,20),'M3U legacy TTL preserved');
delete from public.cloud_catalog_visible_sources where id=pg_temp.id(20);
select pg_temp.assert(pg_temp.blocked(6,20),'M3U hidden source remains closed');
insert into public.cloud_catalog_visible_sources values(pg_temp.id(20),pg_temp.id(6));
update public.cloud_sources set source_type='unsupported' where id=pg_temp.id(20);
select pg_temp.assert(pg_temp.blocked(6,20),'unknown source type fails closed');
select pg_temp.assert(not has_function_privilege('anon','public.catalog_source_account_pregen_active(uuid,uuid)','EXECUTE'),'anonymous ACL denied');
select pg_temp.assert(not has_function_privilege('authenticated','public.catalog_source_account_pregen_active(uuid,uuid)','EXECUTE'),'authenticated ACL denied');
select pg_temp.assert(has_function_privilege('service_role','public.catalog_source_account_pregen_active(uuid,uuid)','EXECUTE'),'service role ACL allowed');
set local request.jwt.claim.role='authenticated';
do $$begin
 begin perform pg_temp.blocked(); raise exception 'service role guard did not reject';
 exception when insufficient_privilege then insert into qa_results values('service role checked inside SECURITY DEFINER'); end;
end $$;
select jsonb_build_object('assertions',count(*),'labels',jsonb_agg(label),'success',true) from qa_results;
rollback;
