-- Generated by scripts/build-branded-email-migration.js. Presentation only.
set lock_timeout='3s';
set statement_timeout='30s';
create or replace function public.norva_branded_email_html(
 p_heading text,p_intro text,p_cta_label text default null,p_cta_url text default null,
 p_footer text default 'If you didn''t request this, please review your account security.'
) returns text language sql immutable set search_path='pg_catalog','public' as $email$
 select case when nullif(btrim(p_cta_label),'') is not null and nullif(btrim(p_cta_url),'') is not null
 then '<!doctype html>
<html lang="en" dir="ltr"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting"><meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no">
<meta name="color-scheme" content="dark"><meta name="supported-color-schemes" content="dark">
<title>' ||
public.norva_html_escape(p_heading) ||
'</title>
<style>body,table,td,a{-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}table,td{mso-table-lspace:0pt;mso-table-rspace:0pt}a:focus-visible{outline:2px solid #60A5FA;outline-offset:4px}a:hover{filter:brightness(1.08)}@media only screen and (max-width:620px){.nv-wrap{padding:24px 12px!important}.nv-pad{padding-left:24px!important;padding-right:24px!important}.nv-title{font-size:28px!important;line-height:35px!important}.nv-brand{padding:0 12px 24px!important}}</style>
</head><body style="margin:0;padding:0;background-color:#080B12;color:#F8FAFC">
<div data-preheader="true" style="display:none!important;visibility:hidden;opacity:0;color:transparent;height:0;width:0;max-height:0;max-width:0;overflow:hidden;mso-hide:all">' ||
public.norva_html_escape(p_heading) ||
'&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</div>
<table role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#080B12" style="width:100%;background-color:#080B12;background-image:radial-gradient(ellipse at 18% 0%,rgba(59,130,246,.13),transparent 52%),radial-gradient(ellipse at 100% 70%,rgba(139,92,246,.09),transparent 50%);border-collapse:collapse">
<tr><td class="nv-wrap" align="center" style="padding:48px 24px">
<!--[if mso]><table role="presentation" width="600" align="center" border="0" cellpadding="0" cellspacing="0"><tr><td><![endif]-->
<table role="presentation" width="600" border="0" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;border-collapse:separate">
<tr><td class="nv-brand" style="padding:0 8px 32px"><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr>
<td width="40" style="width:40px"><img src="https://norva.tv/img/norva-app-icon.png" width="40" height="40" alt="" aria-hidden="true" style="display:block;width:40px;height:40px;border:0;border-radius:10px;outline:none;text-decoration:none"></td>
<td style="padding-left:12px;color:#F8FAFC;font-family:Outfit,Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:26px;font-weight:600;line-height:32px;letter-spacing:-.6px">Norva</td>
</tr></table></td></tr>
<tr><td bgcolor="#12121a" style="background-color:#12121a;background-image:linear-gradient(135deg,rgba(96,165,250,.14) 0%,rgba(18,18,26,.8) 43%,rgba(139,92,246,.08) 100%);border:1px solid #3f3f46;border-top-color:#64748b;border-radius:16px;box-shadow:inset 0 1px 0 rgba(255,255,255,.13),0 24px 64px rgba(0,0,0,.3);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px)">
<table role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0" style="width:100%;table-layout:fixed;border-collapse:separate">
<tr><td class="nv-pad" style="padding:32px 40px 0"><img src="https://norva.tv/img/email/' ||
case when p_heading ilike '%trial%' or p_heading ilike '%subscription%' or p_heading ilike '%payment%' then 'billing' when p_heading ilike '%partner%' or p_heading ilike '%support%' then 'support' else 'security' end ||
'-v1.jpg" width="518" height="173" alt="" aria-hidden="true" style="display:block;width:100%;max-width:518px;height:auto;border:0;border-radius:10px;outline:none;text-decoration:none"></td></tr>
<tr><td class="nv-pad" style="padding:40px 40px 16px"><h1 class="nv-title" style="margin:0;color:#F8FAFC;font-family:Outfit,Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:34px;font-weight:600;line-height:41px;letter-spacing:-1px;overflow-wrap:break-word">' ||
public.norva_html_escape(p_heading) ||
'</h1></td></tr>
<tr><td class="nv-pad" style="padding:8px 40px 24px;color:#cbd5e1;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:16px;line-height:27px;overflow-wrap:break-word">' ||
coalesce(p_intro, '') ||
'</td></tr>
<tr><td class="nv-pad" style="padding:8px 40px 32px">
    <table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td bgcolor="#2563EB" style="background-color:#2563EB;background-image:linear-gradient(135deg,#2563EB,#1D4ED8);border:1px solid #60A5FA;border-radius:10px;box-shadow:0 8px 24px rgba(37,99,235,.24);mso-padding-alt:16px 24px">
    <a href="' ||
public.norva_html_escape(p_cta_url) ||
'" style="display:inline-block;padding:16px 24px;color:#ffffff;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:16px;font-weight:600;line-height:24px;text-decoration:none;text-align:center">' ||
public.norva_html_escape(p_cta_label) ||
'</a>
    </td></tr></table></td></tr><tr><td class="nv-pad" style="padding:24px 40px 32px;border-top:1px solid #27272a;color:#94A3B8;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:14px;line-height:23px">' ||
public.norva_html_escape(p_footer) ||
'</td></tr>
</table></td></tr>
<tr><td class="nv-pad" style="padding:24px 8px 0;color:#94A3B8;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:13px;line-height:22px">&copy; Norva</td></tr>
</table>
<!--[if mso]></td></tr></table><![endif]-->
</td></tr></table></body></html>'
 else '<!doctype html>
<html lang="en" dir="ltr"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting"><meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no">
<meta name="color-scheme" content="dark"><meta name="supported-color-schemes" content="dark">
<title>' ||
public.norva_html_escape(p_heading) ||
'</title>
<style>body,table,td,a{-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}table,td{mso-table-lspace:0pt;mso-table-rspace:0pt}a:focus-visible{outline:2px solid #60A5FA;outline-offset:4px}a:hover{filter:brightness(1.08)}@media only screen and (max-width:620px){.nv-wrap{padding:24px 12px!important}.nv-pad{padding-left:24px!important;padding-right:24px!important}.nv-title{font-size:28px!important;line-height:35px!important}.nv-brand{padding:0 12px 24px!important}}</style>
</head><body style="margin:0;padding:0;background-color:#080B12;color:#F8FAFC">
<div data-preheader="true" style="display:none!important;visibility:hidden;opacity:0;color:transparent;height:0;width:0;max-height:0;max-width:0;overflow:hidden;mso-hide:all">' ||
public.norva_html_escape(p_heading) ||
'&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</div>
<table role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#080B12" style="width:100%;background-color:#080B12;background-image:radial-gradient(ellipse at 18% 0%,rgba(59,130,246,.13),transparent 52%),radial-gradient(ellipse at 100% 70%,rgba(139,92,246,.09),transparent 50%);border-collapse:collapse">
<tr><td class="nv-wrap" align="center" style="padding:48px 24px">
<!--[if mso]><table role="presentation" width="600" align="center" border="0" cellpadding="0" cellspacing="0"><tr><td><![endif]-->
<table role="presentation" width="600" border="0" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;border-collapse:separate">
<tr><td class="nv-brand" style="padding:0 8px 32px"><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr>
<td width="40" style="width:40px"><img src="https://norva.tv/img/norva-app-icon.png" width="40" height="40" alt="" aria-hidden="true" style="display:block;width:40px;height:40px;border:0;border-radius:10px;outline:none;text-decoration:none"></td>
<td style="padding-left:12px;color:#F8FAFC;font-family:Outfit,Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:26px;font-weight:600;line-height:32px;letter-spacing:-.6px">Norva</td>
</tr></table></td></tr>
<tr><td bgcolor="#12121a" style="background-color:#12121a;background-image:linear-gradient(135deg,rgba(96,165,250,.14) 0%,rgba(18,18,26,.8) 43%,rgba(139,92,246,.08) 100%);border:1px solid #3f3f46;border-top-color:#64748b;border-radius:16px;box-shadow:inset 0 1px 0 rgba(255,255,255,.13),0 24px 64px rgba(0,0,0,.3);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px)">
<table role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0" style="width:100%;table-layout:fixed;border-collapse:separate">
<tr><td class="nv-pad" style="padding:32px 40px 0"><img src="https://norva.tv/img/email/' ||
case when p_heading ilike '%trial%' or p_heading ilike '%subscription%' or p_heading ilike '%payment%' then 'billing' when p_heading ilike '%partner%' or p_heading ilike '%support%' then 'support' else 'security' end ||
'-v1.jpg" width="518" height="173" alt="" aria-hidden="true" style="display:block;width:100%;max-width:518px;height:auto;border:0;border-radius:10px;outline:none;text-decoration:none"></td></tr>
<tr><td class="nv-pad" style="padding:40px 40px 16px"><h1 class="nv-title" style="margin:0;color:#F8FAFC;font-family:Outfit,Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:34px;font-weight:600;line-height:41px;letter-spacing:-1px;overflow-wrap:break-word">' ||
public.norva_html_escape(p_heading) ||
'</h1></td></tr>
<tr><td class="nv-pad" style="padding:8px 40px 24px;color:#cbd5e1;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:16px;line-height:27px;overflow-wrap:break-word">' ||
coalesce(p_intro, '') ||
'</td></tr>
<tr><td class="nv-pad" style="padding:24px 40px 32px;border-top:1px solid #27272a;color:#94A3B8;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:14px;line-height:23px">' ||
public.norva_html_escape(p_footer) ||
'</td></tr>
</table></td></tr>
<tr><td class="nv-pad" style="padding:24px 8px 0;color:#94A3B8;font-family:Inter,-apple-system,BlinkMacSystemFont,''Segoe UI'',Arial,Helvetica,sans-serif;font-size:13px;line-height:22px">&copy; Norva</td></tr>
</table>
<!--[if mso]></td></tr></table><![endif]-->
</td></tr></table></body></html>' end;
$email$;
