-- Generated by branded-service-v1/prepare.mjs; installed only with the explicit disabled gate.
begin;
set local lock_timeout='1500ms';
set local statement_timeout='30s';
select pg_advisory_xact_lock(1788678295);
do $guard$ begin
if current_user <> 'supabase_admin' or current_setting('norva.postal_install',true) is distinct from 'branded-v1-disabled' then raise exception 'explicit_disabled_install_required'; end if;
if (select pg_get_userbyid(relowner) from pg_class where oid='public.cloud_branded_email_outbox'::regclass) is distinct from 'supabase_admin' or (select pg_get_userbyid(relowner) from pg_class where oid='public.cloud_email_suppressions'::regclass) is distinct from 'supabase_admin' then raise exception 'unexpected_live_owner';end if;
if to_regnamespace('norva_postal_queue') is not null or exists(select 1 from pg_roles where rolname='norva_postal_branded_worker') then raise exception 'fresh_install_only'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.claim_branded_email_deliveries(integer,integer,integer)')) is distinct from '682e69b24d8d4838ba0e3357df7ecb9a' then raise exception 'baseline_changed:claim_branded_email_deliveries'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.complete_branded_email_delivery(uuid,text,uuid,text,integer,jsonb)')) is distinct from '82fa003d187803a69c237c87161e9f2e' then raise exception 'baseline_changed:complete_branded_email_delivery'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.fail_branded_email_delivery(uuid,text,uuid,integer,text,jsonb,boolean,integer,integer)')) is distinct from '60aa3bdc703cd1f3b2305d2dbb3adb23' then raise exception 'baseline_changed:fail_branded_email_delivery'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.fail_branded_email_delivery(uuid,text,uuid,integer,text,jsonb,boolean,integer,integer,boolean)')) is distinct from 'f757e2f86acfd3c98556528a321a01bc' then raise exception 'baseline_changed:fail_branded_email_delivery'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.defer_branded_email_delivery(uuid,text,uuid,integer)')) is distinct from '3e81ff07393c5272e1282b8ccbc043cc' then raise exception 'baseline_changed:defer_branded_email_delivery'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.authorize_branded_email_delivery(uuid,text,uuid)')) is distinct from '5b6c2a5d3c5da60d85b38c473108c803' then raise exception 'baseline_changed:authorize_branded_email_delivery'; end if;
if (select md5(replace(prosrc,chr(13),'')) from pg_proc where oid=to_regprocedure('public.authorize_branded_email_delivery_pre_behavioral(uuid,text,uuid)')) is distinct from 'de501d8c045f90f60bafb4a1b393f956' then raise exception 'baseline_changed:authorize_branded_email_delivery_pre_behavioral'; end if;
end $guard$;
-- Embedded in the guarded offline candidate, NOT in automatic migrations.
lock table public.cloud_branded_email_outbox in share row exclusive mode;
create temporary table postal_install_before on commit drop as select id,md5(to_jsonb(o)::text) fingerprint from public.cloud_branded_email_outbox o;
create schema norva_postal_queue;
revoke all on schema norva_postal_queue from public,anon,authenticated,service_role;
alter table public.cloud_branded_email_outbox
  add column mail_provider text not null default 'resend' check(mail_provider in ('resend','postal')),
  add column postal_message_id bigint check(postal_message_id between 1 and 9007199254740991),
  add column postal_response jsonb,
  add constraint branded_provider_receipt_bound check (
    (mail_provider='resend' and postal_message_id is null and postal_response is null)
    or (mail_provider='postal' and resend_email_id is null and resend_response is null));
create unique index on public.cloud_branded_email_outbox(postal_message_id) where postal_message_id is not null;
alter table public.cloud_email_suppressions add column postal_review_required_at timestamptz;
create function norva_postal_queue.guard_suppression() returns trigger
language plpgsql security definer set search_path=pg_catalog as $$
begin
  new.postal_review_required_at:=greatest(new.postal_review_required_at,
    case when tg_op='UPDATE' then old.postal_review_required_at end);
  if new.postal_review_required_at is not null and not new.active then
    raise exception 'postal_exclusion_requires_separate_review';
  end if;
  return new;
end $$;
create trigger norva_postal_suppression_guard before insert or update on public.cloud_email_suppressions
for each row execute function norva_postal_queue.guard_suppression();

create table norva_postal_queue.policy (
  singleton boolean primary key default true check(singleton),
  enabled boolean not null default false,
  expires_at timestamptz,
  max_daily integer not null default 2 check(max_daily between 1 and 10)
);
insert into norva_postal_queue.policy default values;
create table norva_postal_queue.allowlist (
  email text not null check(email=lower(btrim(email)) and length(email) between 3 and 320),
  flow text not null check(flow ~ '^[a-z0-9_]{1,50}$'),
  primary key(email,flow)
);
create table norva_postal_queue.bindings (
  outbox_id uuid primary key references public.cloud_branded_email_outbox(id) on delete cascade,
  recipient_email text not null,
  payload_sha256 text not null check(payload_sha256 ~ '^[0-9a-f]{64}$'),
  state text not null default 'pending' check(state in ('pending','reserved','accepted','uncertain','rejected')),
  attempt_token uuid, reserved_at timestamptz,
  provider_message_id bigint unique check(provider_message_id between 1 and 9007199254740991),
  completed_at timestamptz,
  check((state='accepted') = (provider_message_id is not null)),
  check((state='pending') = (attempt_token is null)),
  check((state='pending') = (reserved_at is null))
);
alter table norva_postal_queue.policy enable row level security;
alter table norva_postal_queue.allowlist enable row level security;
alter table norva_postal_queue.bindings enable row level security;
revoke all on all tables in schema norva_postal_queue from public,anon,authenticated,service_role;

create function norva_postal_queue.payload_hash(o public.cloud_branded_email_outbox)
returns text language sql immutable set search_path=pg_catalog as $$
select encode(sha256(convert_to(jsonb_build_array(o.delivery_key,o.user_id,o.flow,o.is_marketing,
  o.recipient_email,o.request_from,o.request_reply_to,o.request_subject,o.request_html,o.request_text,
  o.request_tags,o.request_headers,o.marker_kind,o.marker_reference,o.marker_stage)::text,'UTF8')),'hex')
$$;

-- A service-role table write may not opt into Postal, replace the request or
-- fabricate a Postal receipt. Only the narrow SECURITY DEFINER procedures do so.
create function norva_postal_queue.guard_business_row() returns trigger
language plpgsql set search_path=pg_catalog as $$
begin
  if current_user <> 'supabase_admin' and (
    new.mail_provider='postal' or (tg_op='UPDATE' and old.mail_provider='postal')) then
    raise exception 'postal_row_requires_narrow_procedure';
  end if;
  if tg_op='UPDATE' and old.mail_provider='postal' then
    if new.mail_provider<>'postal' then raise exception 'postal_provider_is_immutable'; end if;
    -- Preserve auth.users ON DELETE SET NULL. A queued message must not prevent
    -- account deletion; cancel/scrub it. A simultaneous in-flight reservation
    -- stays held for reconciliation and cannot become a second send.
    if old.user_id is not null and new.user_id is null and new.state in ('pending','processing') then
      new.state:='canceled'; new.last_error:='account_deleted_before_ack';
      new.lease_token:=null; new.lease_expires_at:=null;
      new.recipient_email:=null; new.request_reply_to:=null; new.request_subject:=null;
      new.request_html:=null; new.request_text:=null; new.request_headers:='{}';
      new.payload_scrubbed_at:=clock_timestamp();
      return new;
    end if;
    if new.state in ('pending','processing') and
      norva_postal_queue.payload_hash(new)<>norva_postal_queue.payload_hash(old) then
      raise exception 'postal_payload_is_immutable';
    end if;
  end if;
  return new;
end $$;

create table norva_postal_queue.events (
  event_id uuid primary key,
  body_sha256 text not null check(body_sha256 ~ '^[0-9a-f]{64}$'),
  outbox_id uuid not null references norva_postal_queue.bindings(outbox_id) on delete cascade,
  event text not null check(event in ('MessageSent','MessageDelayed','MessageDeliveryFailed','MessageHeld','MessageBounced','OperatorVerifiedComplaint')),
  event_at timestamptz not null,
  received_at timestamptz not null default clock_timestamp()
);
alter table norva_postal_queue.events enable row level security;
revoke all on norva_postal_queue.events from public,anon,authenticated,service_role;

create function norva_postal_queue.apply_event(p_event_id uuid,p_body_sha256 text,p_delivery_key text,
  p_message_id bigint,p_event text,p_event_at timestamptz) returns text
language plpgsql security definer set search_path=pg_catalog as $$
declare b norva_postal_queue.bindings%rowtype; previous norva_postal_queue.events%rowtype;
begin
  if p_event_id is null or p_body_sha256 is null or p_body_sha256 !~ '^[0-9a-f]{64}$'
    or p_event is null or p_event not in ('MessageSent','MessageDelayed','MessageDeliveryFailed','MessageHeld','MessageBounced')
    or p_event_at is null or p_event_at>clock_timestamp()+interval '5 minutes'
    or p_event_at<clock_timestamp()-interval '48 hours' then raise exception 'invalid_verified_event'; end if;
  -- Serialize the UUID as well as the receipt. No acknowledgement before both
  -- event replay protection and common suppression update have committed.
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text,42));
  select * into previous from norva_postal_queue.events where event_id=p_event_id;
  if found then
    if previous.body_sha256=p_body_sha256 then return 'duplicate'; else return 'conflict'; end if;
  end if;
  select x.* into b from norva_postal_queue.bindings x join public.cloud_branded_email_outbox o on o.id=x.outbox_id
    where x.state='accepted' and x.provider_message_id=p_message_id and o.delivery_key=p_delivery_key
      and o.mail_provider='postal' for update of x;
  if not found then return 'receipt_not_bound'; end if;
  insert into norva_postal_queue.events(event_id,body_sha256,outbox_id,event,event_at)
    values(p_event_id,p_body_sha256,b.outbox_id,p_event,p_event_at);
  if p_event='MessageBounced' then
    -- A Postal bounce alone is NOT proof of permanent address invalidity. Stop
    -- further sends pending review; never invent a DSN class or auto-unsuppress.
    insert into public.cloud_email_suppressions(email,reason,source_event_id,source_email_id,active,first_seen_at,last_seen_at,postal_review_required_at)
      values(lower(b.recipient_email),'postal_bounce_pending_review','postal:'||p_event_id::text,
        'postal:'||p_message_id::text,true,p_event_at,p_event_at,p_event_at)
      on conflict(email) do update set active=true,resolved_at=null,
        source_event_id=excluded.source_event_id,source_email_id=excluded.source_email_id,
        reason=case when public.cloud_email_suppressions.complaint_seen_at is not null
          then public.cloud_email_suppressions.reason else excluded.reason end,
        postal_review_required_at=greatest(public.cloud_email_suppressions.postal_review_required_at,p_event_at),
        last_seen_at=greatest(public.cloud_email_suppressions.last_seen_at,excluded.last_seen_at),
        updated_at=clock_timestamp();
  end if;
  -- MessageSent never clears a bounce/complaint or claims inbox placement.
  return 'applied';
end $$;

-- Postal's documented events do NOT include a complaint webhook. Until an
-- authenticated JMRP/ARF intake is implemented, this requires operator-reviewed
-- evidence. No public endpoint or service-role grant accepts claimed complaints.
create function norva_postal_queue.record_verified_complaint(p_message_id bigint,p_evidence_sha256 text)
returns boolean language plpgsql security definer set search_path=pg_catalog as $$
declare b norva_postal_queue.bindings%rowtype; v_now timestamptz:=clock_timestamp();
begin
  if p_evidence_sha256 is null or p_evidence_sha256 !~ '^[0-9a-f]{64}$' then raise exception 'evidence_required'; end if;
  select * into b from norva_postal_queue.bindings where state='accepted' and provider_message_id=p_message_id for update;
  if not found then return false; end if;
  if exists(select 1 from norva_postal_queue.events where outbox_id=b.outbox_id
    and event='OperatorVerifiedComplaint' and body_sha256=p_evidence_sha256) then return true; end if;
  insert into norva_postal_queue.events(event_id,body_sha256,outbox_id,event,event_at)
    values(gen_random_uuid(),p_evidence_sha256,b.outbox_id,'OperatorVerifiedComplaint',v_now);
  insert into public.cloud_email_suppressions(email,reason,source_event_id,source_email_id,active,
    first_seen_at,last_seen_at,complaint_seen_at,postal_review_required_at)
    values(lower(b.recipient_email),'postal_verified_complaint','postal-evidence:'||p_evidence_sha256,
      'postal:'||p_message_id::text,true,v_now,v_now,v_now,v_now)
    on conflict(email) do update set active=true,resolved_at=null,
      reason='postal_verified_complaint',complaint_seen_at=coalesce(public.cloud_email_suppressions.complaint_seen_at,v_now),
      postal_review_required_at=greatest(public.cloud_email_suppressions.postal_review_required_at,v_now),
      last_seen_at=greatest(public.cloud_email_suppressions.last_seen_at,v_now),updated_at=v_now;
  return true;
end $$;
create trigger norva_postal_business_guard before insert or update on public.cloud_branded_email_outbox
for each row execute function norva_postal_queue.guard_business_row();

-- Operator only; no grant to service_role. Existing/attempted Resend rows never
-- move providers. There is deliberately no automatic catch-up or global toggle.
create function norva_postal_queue.enroll(p_id uuid) returns boolean
language plpgsql security definer set search_path=pg_catalog as $$
declare o public.cloud_branded_email_outbox%rowtype;
begin
  select * into o from public.cloud_branded_email_outbox where id=p_id for update;
  if not found or o.mail_provider<>'resend' or o.state<>'pending' or o.attempt_count<>0 or o.user_id is null
     or o.transport_started_at is not null or o.resend_email_id is not null
     or o.resend_response is not null or o.created_at<clock_timestamp()-interval '1 hour'
     or not exists(select 1 from norva_postal_queue.allowlist where email=o.recipient_email and flow=o.flow)
     or exists(select 1 from public.cloud_email_suppressions where email=lower(o.recipient_email) and active)
     or (select count(distinct email) from norva_postal_queue.allowlist)>2 then return false; end if;
  insert into norva_postal_queue.bindings(outbox_id,recipient_email,payload_sha256)
  values(o.id,o.recipient_email,norva_postal_queue.payload_hash(o));
  update public.cloud_branded_email_outbox set mail_provider='postal' where id=o.id;
  return true;
end $$;

create function norva_postal_queue.claim() returns jsonb
language plpgsql security definer set search_path=pg_catalog as $$
declare o public.cloud_branded_email_outbox%rowtype;
begin
  if not exists(select 1 from norva_postal_queue.policy where enabled and expires_at>clock_timestamp()
    and expires_at<=clock_timestamp()+interval '24 hours') then return null; end if;
  select x.* into o from public.cloud_branded_email_outbox x
  join norva_postal_queue.bindings b on b.outbox_id=x.id and b.state='pending'
  where x.mail_provider='postal' and x.next_attempt_at<=clock_timestamp()
    and (x.state='pending' or (x.state='processing' and x.lease_expires_at<=clock_timestamp()))
  order by x.created_at limit 1 for update of x skip locked;
  if not found then return null; end if;
  update public.cloud_branded_email_outbox set state='processing',lease_token=gen_random_uuid(),
    lease_expires_at=clock_timestamp()+interval '90 seconds',attempt_count=attempt_count+1,
    last_attempt_at=clock_timestamp(),updated_at=clock_timestamp() where id=o.id returning * into o;
  return jsonb_build_object('id',o.id,'delivery_key',o.delivery_key,'lease_token',o.lease_token);
end $$;

create function norva_postal_queue.reserve(p_id uuid,p_delivery_key text,p_lease_token uuid) returns jsonb
language plpgsql security definer set search_path=pg_catalog as $$
declare o public.cloud_branded_email_outbox%rowtype; b norva_postal_queue.bindings%rowtype;
  cfg norva_postal_queue.policy%rowtype; token uuid;
begin
  select * into strict cfg from norva_postal_queue.policy where singleton for update;
  select * into b from norva_postal_queue.bindings where outbox_id=p_id for update;
  if not found or b.state<>'pending' then return jsonb_build_object('state','held'); end if;
  select * into o from public.cloud_branded_email_outbox where id=p_id and delivery_key=p_delivery_key
    and mail_provider='postal' and state='processing' and lease_token=p_lease_token
    and lease_expires_at>clock_timestamp() for update;
  if not found then return jsonb_build_object('state','lease_lost'); end if;
  if not cfg.enabled or cfg.expires_at is null or cfg.expires_at<=clock_timestamp()
    or cfg.expires_at>clock_timestamp()+interval '24 hours'
    or (select count(distinct email) from norva_postal_queue.allowlist)>2
    or not exists(select 1 from norva_postal_queue.allowlist where email=o.recipient_email and flow=o.flow)
    or (select count(*) from norva_postal_queue.bindings where reserved_at>clock_timestamp()-interval '24 hours')>=cfg.max_daily
    then return jsonb_build_object('state','policy_blocked'); end if;
  if exists(select 1 from public.cloud_email_suppressions where email=lower(o.recipient_email) and active) then
    update public.cloud_branded_email_outbox set state='canceled',last_error='email_suppressed',
      lease_token=null,lease_expires_at=null,recipient_email=null,request_reply_to=null,request_subject=null,
      request_html=null,request_text=null,request_headers='{}',payload_scrubbed_at=clock_timestamp()
      where id=p_id;
    return jsonb_build_object('state','suppressed');
  end if;
  if norva_postal_queue.payload_hash(o)<>b.payload_sha256 then raise exception 'bound_payload_changed'; end if;
  -- Actual Norva gate: includes consent, current conversion, quiet hours and caps.
  if not public.authorize_branded_email_delivery(p_id,p_delivery_key,p_lease_token) then
    return jsonb_build_object('state','authorization_denied_or_deferred');
  end if;
  token:=gen_random_uuid();
  update norva_postal_queue.bindings set state='reserved',attempt_token=token,reserved_at=clock_timestamp()
    where outbox_id=p_id;
  return jsonb_build_object('state','reserved','attempt_token',token,'id',o.id,'delivery_key',o.delivery_key,
    'provider','postal','payload_sha256',b.payload_sha256,'recipient_email',o.recipient_email,
    'request_from',o.request_from,'request_reply_to',o.request_reply_to,'request_subject',o.request_subject,
    'request_html',o.request_html,'request_text',o.request_text,'request_headers',o.request_headers,
    'request_tags',o.request_tags,'is_marketing',o.is_marketing);
end $$;

-- Acceptance is durably bound BEFORE the business acknowledgement. If the
-- following acknowledgement transaction fails, reconcile() does no network I/O.
create function norva_postal_queue.finish(p_id uuid,p_attempt_token uuid,p_state text,p_message_id bigint default null)
returns boolean language plpgsql security definer set search_path=pg_catalog as $$
declare b norva_postal_queue.bindings%rowtype;
begin
  if p_state is null or p_state not in ('accepted','uncertain','rejected')
    or (p_state='accepted' and (p_message_id is null or p_message_id not between 1 and 9007199254740991))
    or (p_state<>'accepted' and p_message_id is not null) then raise exception 'invalid_receipt'; end if;
  select * into b from norva_postal_queue.bindings where outbox_id=p_id for update;
  if not found or p_attempt_token is null or b.attempt_token<>p_attempt_token then return false; end if;
  if b.state='accepted' then return p_state='accepted' and b.provider_message_id=p_message_id; end if;
  if b.state<>'reserved' then return false; end if;
  update norva_postal_queue.bindings set state=p_state,provider_message_id=p_message_id where outbox_id=p_id;
  if p_state<>'accepted' then
    update public.cloud_branded_email_outbox set state='dead_letter',dead_lettered_at=clock_timestamp(),
      last_error=case when p_state='uncertain' then 'postal_outcome_unknown_do_not_replay' else 'postal_rejected' end,
      lease_token=null,lease_expires_at=null,updated_at=clock_timestamp() where id=p_id and state='processing';
  end if;
  return true;
end $$;

create table norva_postal_queue.smtp_attempts (
 outbox_id uuid primary key references norva_postal_queue.bindings(outbox_id) on delete cascade,
 permit uuid not null unique,
 expires_at timestamptz not null,
 reserved_at timestamptz not null default clock_timestamp(),
 state text not null default 'reserved' check(state in ('reserved','Sent','Held','HardFail')),
 secure boolean not null default false,
 finished_at timestamptz,
 check(state<>'Sent' or secure),
 check((state='reserved')=(finished_at is null))
);
alter table norva_postal_queue.smtp_attempts enable row level security;
revoke all on norva_postal_queue.smtp_attempts from public,anon,authenticated,service_role;
create index norva_postal_pending_business on public.cloud_branded_email_outbox(next_attempt_at,created_at)
 where mail_provider='postal' and state in ('pending','processing');


create function norva_postal_queue.reconcile(p_id uuid) returns boolean
language plpgsql security definer set search_path=pg_catalog as $$
declare b norva_postal_queue.bindings%rowtype; o public.cloud_branded_email_outbox%rowtype; done boolean;
begin
  select * into b from norva_postal_queue.bindings where outbox_id=p_id for update;
  if not found or b.state<>'accepted' or not exists(select 1 from norva_postal_queue.smtp_attempts s where s.outbox_id=p_id and s.state='Sent' and s.secure) then return false; end if;
  select * into o from public.cloud_branded_email_outbox where id=p_id and mail_provider='postal' for update;
  if not found then return false; end if;
  if o.state='sent' then return o.postal_message_id=b.provider_message_id; end if;
  if o.state<>'processing' then return false; end if;
  done:=norva_postal_queue.complete_business_markers(o.id,o.delivery_key,o.lease_token,b.provider_message_id::text,200,
    jsonb_build_object('provider','postal','id',b.provider_message_id,'inbox_delivery_proven',false));
  if done then update norva_postal_queue.bindings set completed_at=clock_timestamp() where outbox_id=p_id; end if;
  return done;
end $$;

create function norva_postal_queue.reconcile_pending() returns integer
language plpgsql security definer set search_path=pg_catalog as $$
declare r record; n integer:=0;
begin
  for r in select b.outbox_id from norva_postal_queue.bindings b
    join public.cloud_branded_email_outbox o on o.id=b.outbox_id
    where b.state='accepted' and b.completed_at is null and o.state='processing'
    order by b.reserved_at limit 10 for update of b skip locked loop
    if norva_postal_queue.reconcile(r.outbox_id) then n:=n+1; end if;
  end loop;
  return n;
end $$;

create or replace function norva_postal_queue.complete_business_markers(
  p_id uuid, p_delivery_key text, p_lease_token uuid, p_postal_message_id text,
  p_http_status integer, p_response jsonb default '{}'::jsonb
) returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  o record;
  v_now timestamptz := clock_timestamp();
begin
  if p_http_status not between 200 and 299 or nullif(btrim(p_postal_message_id),'') is null then
    raise exception 'successful Postal status and message id are required';
  end if;
  select * into o from public.cloud_branded_email_outbox x
  where x.mail_provider='postal' and x.id=p_id and x.delivery_key=p_delivery_key
    and x.state='processing' and x.lease_token=p_lease_token
  for update;
  if not found then return false; end if;

  update public.cloud_branded_email_outbox x
  set state='sent', postal_message_id=p_postal_message_id::bigint,
      postal_response=coalesce(p_response,'{}'::jsonb), last_http_status=p_http_status,
      last_error=null, sent_at=v_now, dead_lettered_at=null,
      lease_token=null, lease_expires_at=null, next_attempt_at=v_now,
      recipient_email=null, request_reply_to=null, request_subject=null,
      request_html=null, request_text=null, request_headers='{}'::jsonb,
      payload_scrubbed_at=v_now, updated_at=v_now
  where x.id=p_id and x.state='processing' and x.lease_token=p_lease_token;

  if o.marker_kind = 'welcome' then
    update public.cloud_entitlement_projection e
    set welcome_email_at=coalesce(e.welcome_email_at,v_now) where e.user_id=o.user_id;
  elsif o.marker_kind = 'dunning' then
    update public.cloud_entitlement_projection e
    set dunning_stage=greatest(coalesce(e.dunning_stage,0),o.marker_stage), dunning_last_at=v_now
    where e.user_id=o.user_id and e.status='past_due';
  elsif o.marker_kind = 'winback' then
    update public.cloud_entitlement_projection e
    set winback_email_at=coalesce(e.winback_email_at,v_now) where e.user_id=o.user_id;
  elsif o.marker_kind = 'abandoned' then
    update public.cloud_revolut_orders r
    set reminder_sent_at=coalesce(r.reminder_sent_at,v_now), reminder_claimed_at=null, updated_at=v_now
    where r.order_id=o.marker_reference and r.user_id=o.user_id;
  end if;

  update public.cloud_trial_reminder_deliveries d
  set delivered_at=coalesce(d.delivered_at,v_now)
  where d.email_delivery_id=o.id;
  update public.cloud_entitlement_projection e
  set trial_reminder_email_at=coalesce(e.trial_reminder_email_at,v_now)
  where exists (
    select 1 from public.cloud_trial_reminder_deliveries d
    where d.email_delivery_id=o.id and d.user_id=e.user_id and d.trial_ends_at=e.trial_ends_at
  );
  return true;
end
$function$;
create or replace function public.claim_branded_email_deliveries(
  p_batch integer default 4,
  p_lease_seconds integer default 90,
  p_max_attempts integer default 12
) returns table (
  id uuid, delivery_key text, lease_token uuid, flow text, user_id uuid,
  is_marketing boolean, marker_kind text, marker_reference text, marker_stage smallint,
  recipient_email text, request_from text, request_reply_to text, request_subject text,
  request_html text, request_text text, request_tags jsonb, request_headers jsonb,
  attempt_count integer
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_now timestamptz := clock_timestamp();
begin
  update public.cloud_branded_email_outbox o
  set state = 'dead_letter', dead_lettered_at = v_now,
      last_error = 'ambiguous_delivery_after_idempotency_window',
      lease_token = null, lease_expires_at = null, updated_at = v_now
  where o.mail_provider='resend' and o.state in ('pending', 'processing')
    and o.transport_started_at <= v_now - interval '23 hours';

  return query
  with due as (
    select o.id from public.cloud_branded_email_outbox o
    where o.mail_provider='resend' and o.next_attempt_at <= v_now
      and (o.transport_started_at is null or o.transport_started_at > v_now - interval '23 hours')
      and ((o.state = 'pending' and o.attempt_count < greatest(1, least(coalesce(p_max_attempts,12),30)))
        or (o.state = 'processing' and o.lease_expires_at <= v_now))
    order by o.next_attempt_at, o.created_at
    limit greatest(1, least(coalesce(p_batch,4),20))
    for update skip locked
  ), claimed as (
    update public.cloud_branded_email_outbox o
    set state = 'processing', lease_token = gen_random_uuid(),
        lease_expires_at = v_now + make_interval(secs => greatest(30,least(coalesce(p_lease_seconds,90),300))),
        attempt_count = o.attempt_count + 1, last_attempt_at = v_now,
        updated_at = v_now
    from due where o.id = due.id returning o.*
  )
  select c.id, c.delivery_key, c.lease_token, c.flow, c.user_id,
         c.is_marketing, c.marker_kind, c.marker_reference, c.marker_stage,
         c.recipient_email, c.request_from, c.request_reply_to, c.request_subject,
         c.request_html, c.request_text, c.request_tags, c.request_headers,
         c.attempt_count
  from claimed c order by c.next_attempt_at, c.created_at;
end
$function$;
create or replace function public.complete_branded_email_delivery(
  p_id uuid, p_delivery_key text, p_lease_token uuid, p_resend_email_id text,
  p_http_status integer, p_response jsonb default '{}'::jsonb
) returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  o record;
  v_now timestamptz := clock_timestamp();
begin
  if p_http_status not between 200 and 299 or nullif(btrim(p_resend_email_id),'') is null then
    raise exception 'successful Resend status and email id are required';
  end if;
  select * into o from public.cloud_branded_email_outbox x
  where x.mail_provider='resend' and x.id=p_id and x.delivery_key=p_delivery_key
    and x.state='processing' and x.lease_token=p_lease_token
  for update;
  if not found then return false; end if;

  update public.cloud_branded_email_outbox x
  set state='sent', resend_email_id=left(btrim(p_resend_email_id),200),
      resend_response=coalesce(p_response,'{}'::jsonb), last_http_status=p_http_status,
      last_error=null, sent_at=v_now, dead_lettered_at=null,
      lease_token=null, lease_expires_at=null, next_attempt_at=v_now,
      recipient_email=null, request_reply_to=null, request_subject=null,
      request_html=null, request_text=null, request_headers='{}'::jsonb,
      payload_scrubbed_at=v_now, updated_at=v_now
  where x.id=p_id and x.state='processing' and x.lease_token=p_lease_token;

  if o.marker_kind = 'welcome' then
    update public.cloud_entitlement_projection e
    set welcome_email_at=coalesce(e.welcome_email_at,v_now) where e.user_id=o.user_id;
  elsif o.marker_kind = 'dunning' then
    update public.cloud_entitlement_projection e
    set dunning_stage=greatest(coalesce(e.dunning_stage,0),o.marker_stage), dunning_last_at=v_now
    where e.user_id=o.user_id and e.status='past_due';
  elsif o.marker_kind = 'winback' then
    update public.cloud_entitlement_projection e
    set winback_email_at=coalesce(e.winback_email_at,v_now) where e.user_id=o.user_id;
  elsif o.marker_kind = 'abandoned' then
    update public.cloud_revolut_orders r
    set reminder_sent_at=coalesce(r.reminder_sent_at,v_now), reminder_claimed_at=null, updated_at=v_now
    where r.order_id=o.marker_reference and r.user_id=o.user_id;
  end if;

  update public.cloud_trial_reminder_deliveries d
  set delivered_at=coalesce(d.delivered_at,v_now)
  where d.email_delivery_id=o.id;
  update public.cloud_entitlement_projection e
  set trial_reminder_email_at=coalesce(e.trial_reminder_email_at,v_now)
  where exists (
    select 1 from public.cloud_trial_reminder_deliveries d
    where d.email_delivery_id=o.id and d.user_id=e.user_id and d.trial_ends_at=e.trial_ends_at
  );
  return true;
end
$function$;
create or replace function public.fail_branded_email_delivery(
  p_id uuid,
  p_delivery_key text,
  p_lease_token uuid,
  p_http_status integer,
  p_error text,
  p_response jsonb default '{}'::jsonb,
  p_retryable boolean default true,
  p_retry_after_seconds integer default null,
  p_max_attempts integer default 12
)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_now timestamptz := clock_timestamp();
  v_attempt integer;
  v_terminal boolean;
  v_delay_seconds integer;
  v_changed integer;
begin
  select o.attempt_count into v_attempt
  from public.cloud_branded_email_outbox o
  where o.mail_provider='resend' and o.id = p_id
    and o.delivery_key = p_delivery_key
    and o.state = 'processing'
    and o.lease_token = p_lease_token
  for update;
  if not found then return 'lease_lost'; end if;

  v_terminal := not coalesce(p_retryable, false)
    or v_attempt >= greatest(1, least(coalesce(p_max_attempts, 12), 30));
  v_delay_seconds := greatest(
    coalesce(p_retry_after_seconds, 0),
    least(21600, round(30 * power(2::numeric, greatest(v_attempt - 1, 0)))::integer)
      + floor(random() * 16)::integer
  );

  update public.cloud_branded_email_outbox o
  set state = case when v_terminal then 'dead_letter' else 'pending' end,
      resend_response = coalesce(p_response, '{}'::jsonb),
      last_http_status = p_http_status,
      last_error = left(coalesce(nullif(p_error, ''), 'delivery_failed'), 1000),
      dead_lettered_at = case when v_terminal then v_now else null end,
      next_attempt_at = case when v_terminal then o.next_attempt_at
                             else v_now + make_interval(secs => v_delay_seconds) end,
      lease_token = null,
      lease_expires_at = null,
      updated_at = v_now
  where o.mail_provider='resend' and o.id = p_id
    and o.delivery_key = p_delivery_key
    and o.state = 'processing'
    and o.lease_token = p_lease_token;
  get diagnostics v_changed = row_count;
  if v_changed <> 1 then return 'lease_lost'; end if;
  return case when v_terminal then 'dead_letter' else 'retry_scheduled' end;
end
$function$;
create or replace function public.fail_branded_email_delivery(
  p_id uuid, p_delivery_key text, p_lease_token uuid, p_http_status integer,
  p_error text, p_response jsonb default '{}'::jsonb, p_retryable boolean default true,
  p_retry_after_seconds integer default null, p_max_attempts integer default 12,
  p_ambiguous boolean default false
) returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_now timestamptz := clock_timestamp();
  o record;
  v_delay integer;
  v_window_terminal boolean;
  v_terminal boolean;
begin
  select * into o from public.cloud_branded_email_outbox x
  where x.mail_provider='resend' and x.id=p_id and x.delivery_key=p_delivery_key
    and x.state='processing' and x.lease_token=p_lease_token for update;
  if not found then return 'lease_lost'; end if;
  v_delay := greatest(coalesce(p_retry_after_seconds,0),
    least(21600,round(30*power(2::numeric,greatest(o.attempt_count-1,0)))::integer)
      + floor(random()*16)::integer);
  v_window_terminal := coalesce(p_ambiguous,false)
    and o.transport_started_at is not null
    and v_now + make_interval(secs=>v_delay) >= o.transport_started_at + interval '23 hours';
  v_terminal := not coalesce(p_retryable,false)
    or o.attempt_count >= greatest(1,least(coalesce(p_max_attempts,12),30))
    or v_window_terminal;
  update public.cloud_branded_email_outbox x
  set state=case when v_terminal then 'dead_letter' else 'pending' end,
      resend_response=coalesce(p_response,'{}'::jsonb), last_http_status=p_http_status,
      last_error=case when v_window_terminal then 'ambiguous_delivery_after_idempotency_window'
        else left(coalesce(nullif(p_error,''),'delivery_failed'),1000) end,
      dead_lettered_at=case when v_terminal then v_now else null end,
      next_attempt_at=case when v_terminal then x.next_attempt_at else v_now+make_interval(secs=>v_delay) end,
      -- A retryable 401/403 proves the request was not accepted. Once the
      -- credential/configuration is repaired it receives a fresh idempotency
      -- window. Ambiguous transport outcomes retain the original timestamp.
      transport_started_at=case
        when coalesce(p_retryable,false) and not coalesce(p_ambiguous,false) then null
        else x.transport_started_at
      end,
      lease_token=null, lease_expires_at=null, updated_at=v_now
  where x.id=p_id and x.state='processing' and x.lease_token=p_lease_token;
  return case when v_terminal then 'dead_letter' else 'retry_scheduled' end;
end
$function$;
create or replace function public.defer_branded_email_delivery(
  p_id uuid, p_delivery_key text, p_lease_token uuid, p_retry_after_seconds integer default 60
) returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare v_changed integer;
begin
  update public.cloud_branded_email_outbox o
  set state='pending', attempt_count=greatest(0,o.attempt_count-1),
      transport_started_at=case when o.attempt_count<=1 then null else o.transport_started_at end,
      next_attempt_at=clock_timestamp()+make_interval(secs=>greatest(1,least(coalesce(p_retry_after_seconds,60),21600))),
      last_http_status=429, last_error='resend_team_rate_limited_before_send',
      resend_response='{"name":"team_rate_limited"}'::jsonb,
      lease_token=null, lease_expires_at=null, updated_at=clock_timestamp()
  where o.mail_provider='resend' and o.id=p_id and o.delivery_key=p_delivery_key
    and o.state='processing' and o.lease_token=p_lease_token;
  get diagnostics v_changed=row_count;
  return v_changed=1;
end
$function$;
revoke all on all functions in schema norva_postal_queue from public,anon,authenticated,service_role;

-- There is deliberately no secret, login, default routing or enabled policy.
create role norva_postal_branded_worker nologin noinherit nosuperuser nocreatedb
 nocreaterole noreplication nobypassrls connection limit 3;
alter role norva_postal_branded_worker set statement_timeout='3s';
alter role norva_postal_branded_worker set lock_timeout='1s';
alter role norva_postal_branded_worker set search_path='pg_catalog';

create function norva_postal_queue.claim_smtp() returns jsonb
language plpgsql security definer set search_path=pg_catalog as $function$
declare cfg norva_postal_queue.policy%rowtype; b norva_postal_queue.bindings%rowtype;
 o public.cloud_branded_email_outbox%rowtype; v_permit uuid; v_expiry timestamptz;
begin
 select * into strict cfg from norva_postal_queue.policy where singleton for update;
 if not cfg.enabled or cfg.expires_at is null or cfg.expires_at<=clock_timestamp()
  or cfg.expires_at>clock_timestamp()+interval '24 hours' then return null; end if;
 select x.* into b from norva_postal_queue.bindings x
 join public.cloud_branded_email_outbox q on q.id=x.outbox_id
 where x.state='accepted' and q.mail_provider='postal' and q.state in ('pending','processing')
  and q.next_attempt_at<=clock_timestamp()
  and not exists(select 1 from norva_postal_queue.smtp_attempts s where s.outbox_id=x.outbox_id)
 order by x.reserved_at limit 1 for update of x skip locked;
 if not found then return null; end if;
 select * into o from public.cloud_branded_email_outbox where id=b.outbox_id for update;
 if o.user_id is null or o.state not in ('pending','processing') or o.mail_provider<>'postal'
  or not exists(select 1 from norva_postal_queue.allowlist where email=o.recipient_email and flow=o.flow)
  or (select count(distinct email) from norva_postal_queue.allowlist)>2
  or (select count(*) from norva_postal_queue.smtp_attempts where reserved_at>clock_timestamp()-interval '24 hours')>=cfg.max_daily
  then return null; end if;
 if exists(select 1 from public.cloud_email_suppressions where email=lower(o.recipient_email) and active) then
  update public.cloud_branded_email_outbox set state='canceled',last_error='email_suppressed_before_smtp',
   lease_token=null,lease_expires_at=null,recipient_email=null,request_reply_to=null,request_subject=null,
   request_html=null,request_text=null,request_headers='{}',payload_scrubbed_at=clock_timestamp()
   where id=o.id;
  return null;
 end if;
 if norva_postal_queue.payload_hash(o)<>b.payload_sha256 then raise exception 'bound_payload_changed'; end if;
 -- A held API message is not sent. Renew only the DB lease and execute the real
 -- business authorization again. Conversion/deletion/consent cancellation wins.
 update public.cloud_branded_email_outbox set state='processing',lease_token=gen_random_uuid(),
  lease_expires_at=clock_timestamp()+interval '90 seconds',updated_at=clock_timestamp()
  where id=o.id returning * into o;
 if not public.authorize_branded_email_delivery(o.id,o.delivery_key,o.lease_token) then return null; end if;
 v_permit:=gen_random_uuid();v_expiry:=least(cfg.expires_at,clock_timestamp()+interval '90 seconds');
 insert into norva_postal_queue.smtp_attempts(outbox_id,permit,expires_at) values(o.id,v_permit,v_expiry);
 return jsonb_build_object('id',o.id,'delivery_key',o.delivery_key,'permit',v_permit,
  'recipient',o.recipient_email,'messageId',b.provider_message_id,
  'expiresUnix',floor(extract(epoch from v_expiry)));
end $function$;

create function norva_postal_queue.smtp_authorized(p_id uuid,p_permit uuid) returns boolean
language plpgsql security definer set search_path=pg_catalog as $function$
declare o public.cloud_branded_email_outbox%rowtype;
begin
 if not exists(select 1 from norva_postal_queue.policy where singleton and enabled
  and expires_at>clock_timestamp() and expires_at<=clock_timestamp()+interval '24 hours') then return false; end if;
 if not exists(select 1 from norva_postal_queue.smtp_attempts where outbox_id=p_id and permit=p_permit
  and state='reserved' and expires_at>clock_timestamp()) then return false; end if;
 select * into o from public.cloud_branded_email_outbox where id=p_id for update;
 if not found or o.mail_provider<>'postal' or o.state<>'processing' or o.user_id is null
  or not exists(select 1 from norva_postal_queue.allowlist where email=o.recipient_email and flow=o.flow)
  or exists(select 1 from public.cloud_email_suppressions where email=lower(o.recipient_email) and active)
  then return false; end if;
 return public.authorize_branded_email_delivery(o.id,o.delivery_key,o.lease_token);
end $function$;

create function norva_postal_queue.finish_smtp(p_id uuid,p_permit uuid,p_state text,p_secure boolean)
returns boolean language plpgsql security definer set search_path=pg_catalog as $function$
declare s norva_postal_queue.smtp_attempts%rowtype;
begin
 if p_state is null or p_state not in ('Sent','Held','HardFail') or p_secure is null
  or (p_state='Sent' and not p_secure) then raise exception 'invalid_smtp_receipt'; end if;
 -- Fixed lock order: binding -> SMTP -> business row.
 perform 1 from norva_postal_queue.bindings where outbox_id=p_id for update;
 select * into s from norva_postal_queue.smtp_attempts where outbox_id=p_id for update;
 if not found or p_permit is null or s.permit<>p_permit then return false; end if;
 if s.state<>'reserved' then return s.state=p_state and s.secure=p_secure; end if;
 update norva_postal_queue.smtp_attempts set state=p_state,secure=p_secure,finished_at=clock_timestamp()
  where outbox_id=p_id;
 if p_state='Sent' then
  -- The receipt is retained even if concurrent account deletion canceled the
  -- business row. Cancellation cannot erase a real SMTP acceptance.
  perform norva_postal_queue.reconcile(p_id);
 else
  update public.cloud_branded_email_outbox set state='dead_letter',dead_lettered_at=clock_timestamp(),
   last_error=case when p_state='Held' then 'postal_smtp_outcome_unknown_no_replay' else 'postal_smtp_rejected' end,
   lease_token=null,lease_expires_at=null,updated_at=clock_timestamp()
   where id=p_id and state in ('pending','processing');
 end if;
 return true;
end $function$;

create function norva_postal_queue.status() returns jsonb
language sql security definer set search_path=pg_catalog as $function$
 select jsonb_build_object('installed',true,'enabled',coalesce((select enabled and
  expires_at>clock_timestamp() from norva_postal_queue.policy where singleton),false),
  'enrolled',(select count(*) from norva_postal_queue.bindings),
  'apiAccepted',(select count(*) from norva_postal_queue.bindings where state='accepted'),
  'smtpSent',(select count(*) from norva_postal_queue.smtp_attempts where state='Sent' and secure),
  'smtpUncertain',(select count(*) from norva_postal_queue.smtp_attempts where state in ('reserved','Held')),
  'feedback',(select count(*) from norva_postal_queue.events),
  'customerRoutingEnabled',false)
$function$;

revoke all on all functions in schema norva_postal_queue from public,anon,authenticated,service_role;
revoke all on all tables in schema norva_postal_queue from public,anon,authenticated,service_role,norva_postal_branded_worker;
grant usage on schema norva_postal_queue to norva_postal_branded_worker;
grant execute on function norva_postal_queue.claim(),norva_postal_queue.reserve(uuid,text,uuid),
 norva_postal_queue.finish(uuid,uuid,text,bigint),norva_postal_queue.reconcile(uuid),
 norva_postal_queue.reconcile_pending(),norva_postal_queue.claim_smtp(),
 norva_postal_queue.smtp_authorized(uuid,uuid),norva_postal_queue.finish_smtp(uuid,uuid,text,boolean),
 norva_postal_queue.apply_event(uuid,text,text,bigint,text,timestamptz),
 norva_postal_queue.status() to norva_postal_branded_worker;
-- No grant for policy, enrollment, complaints or direct business completion.

do $unchanged$ begin
 if exists(select 1 from postal_install_before b left join public.cloud_branded_email_outbox o on o.id=b.id
  where o.id is null or b.fingerprint<>md5((to_jsonb(o)-'mail_provider'-'postal_message_id'-'postal_response')::text)
  or o.mail_provider<>'resend' or o.postal_message_id is not null or o.postal_response is not null)
  then raise exception 'existing_outbox_changed';end if;
 if (select enabled from norva_postal_queue.policy) or exists(select 1 from norva_postal_queue.bindings)
  then raise exception 'installation_must_remain_disabled';end if;
end $unchanged$;
commit;
